### ISSUE TITLE
Map type not supported

### ISSUE THREAD

**Issue by davnoe** [databricks/spark-avro#11]
Exception in thread "main" java.lang.RuntimeException: Unsupported type MAP
	at scala.sys.package$.error(package.scala:27)
    at com.databricks.spark.avro.AvroRelation.com$databricks$spark$avro$AvroRelation$$toSqlType(AvroRelation.scala:116)
    at com.databricks.spark.avro.AvroRelation$$anonfun$5.apply(AvroRelation.scala:97)
    at com.databricks.spark.avro.AvroRelation$$anonfun$5.apply(AvroRelation.scala:96)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)

**Comment by timyitong** [comment]
+1 for this, any plan to support map types?

**Comment by vlyubin** [comment]
The Map type is now supported.
