### ISSUE TITLE
Failed to read avro file 

### ISSUE THREAD

**Issue by corsc** [databricks/spark-avro#131]
I am getting this error while attempting to run my spark app (locally)

`Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving overridden method "com.databricks.spark.avro.AvroRelation.logInfo(Lscala/Function0;)V" the class loader (instance of org/apache/spark/util/ChildFirstURLClassLoader) of the current class, com/databricks/spark/avro/AvroRelation, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type scala/Function0 used in the signature
	at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:30)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:176)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
	at x.x.x.x.X$.main(X.scala:15)
	at x.x.x.x.X.main(X.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

I have tried building this with sbt and mvn and have spent considerable amount of time messing around with the assembly plugin and dependency exclusions on both.

I am happy to provide more info (I am a Scala noob so I don't know what you might want).

**Comment by corsc** [comment]
This seems to be related to scala versions.  My build was 2.11 and Spark is 2.10.

Setting my build file to `2.10.6` and using the brew installed version of spark has resolved the problem.
