### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: org.apache.spark.sql.DataFrame cannot be cast to org.apache.spark.sql.Dataset

### ISSUE THREAD

**Issue by anayyar82** [databricks/spark-avro#151]
Getting issue if i run the job 

Exception in thread "main" java.lang.ClassCastException: org.apache.spark.sql.DataFrame cannot be cast to org.apache.spark.sql.Dataset
	at com.sabre.sparkavro.SparkAvroReader$delayedInit$body.apply(SparkAvroReader.scala:25)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)

**Comment by JoshRosen** [comment]
Which versions of Spark and `spark-avro` are you using?
