### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.load

### ISSUE THREAD

**Issue by kevin-duraj-zefr** [databricks/spark-avro#153]
When executing line 658 reading Avro file from S3
```
val df1  = sqlContext.read.avro(avroFile) 
```

with build.sbt
```
 scalaVersion := "2.11.7"
 
 libraryDependencies ++= Seq(
    "org.apache.spark" % "spark-core_2.11" % "2.0.0",
     "org.apache.spark" % "spark-sql_2.11" % "2.0.0",
     "com.databricks" %% "spark-avro" % "3.0.0",
     "com.amazonaws"     % "aws-java-sdk-s3" % "1.11.3"
 )
```

Getting the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.load(Ljava/lang/String;)Lorg/apache/spark/sql/DataFrame;
	at com.databricks.spark.avro.package$AvroDataFrameReader$$anonfun$avro$2.apply(package.scala:45)
	at com.databricks.spark.avro.package$AvroDataFrameReader$$anonfun$avro$2.apply(package.scala:45)
	at ExportData$.data_transformation_for_index(ExportData.scala:658)
```

**Comment by JoshRosen** [comment]
This looks like a duplicate of #150, but, helpfully, your issue includes the actual version numbers, so I'm going to mark that other issue as a duplicate of this one and will continue investigation here.

I'm a bit puzzled that the `NoSuchMessageError` is referencing a method which returns `org/apache/spark/sql/DataFrame` given that `DataFrame` became [an alias](https://github.com/apache/spark/blob/13650fc58e1fcf2cf2a26ba11c819185ae1acc1f/sql/core/src/main/scala/org/apache/spark/sql/package.scala#L45) for `Dataset[Row]` in Spark 2.0 and this library is compiled against Spark 2.0 and is presumably running against that version.

When I look at `package$AvroDataFrameReader$$anonfun$avro$2.class` using `javap` I see it calling the `Dataset`-returning method:

```
public final org.apache.spark.sql.Dataset<org.apache.spark.sql.Row> apply(java.lang.String);
    descriptor: (Ljava/lang/String;)Lorg/apache/spark/sql/Dataset;
    flags: ACC_PUBLIC, ACC_FINAL
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: getfield      #23                 // Field eta$0$2$1:Lorg/apache/spark/sql/DataFrameReader;
         4: aload_1
         5: invokevirtual #28                 // Method org/apache/spark/sql/DataFrameReader.load:(Ljava/lang/String;)Lorg/apache/spark/sql/Dataset;
         8: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       9     0  this   Lcom/databricks/spark/avro/package$AvroDataFrameReader$$anonfun$avro$2;
            0       9     1  path   Ljava/lang/String;
      LineNumberTable:
        line 34: 0
    Signature: #55                          // (Ljava/lang/String;)Lorg/apache/spark/sql/Dataset<Lorg/apache/spark/sql/Row;>;
```

Given all of this, are you _sure_ that you're using version 3.0.0 of `spark-avro` and don't somehow have an older conflicting version on your classpath?

**Comment by kevin-duraj-zefr** [comment]
I have cleaned old versions and installed everything to the latest version, and I am still getting the same error.

```
rm -fR ~/.ivy2/
rm -fR /usr/local/spark-1.6.1/
yum remove java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64
java -version 
openJDK version "1.8.0_101"
```

**Comment by kevin-duraj-zefr** [comment]
I found the issue, passing wrong version of databricks:spark-avro to spark-submit.

**WRONG:**
```
spark-submit  --packages com.databricks:spark-avro_2.10:2.0.1
```

**RIGHT**
```
spark-submit  --packages com.databricks:spark-avro_2.11:3.0.0 
```
