### ISSUE TITLE
Unable to write data in Avro format with Spark 2.0.0

### ISSUE THREAD

**Issue by Manikantan22** [databricks/spark-avro#166]
I have tried the below code but I couldnt write it as Avro format instead I am getting follwing exception " Failed to find data source: com.databricks.spark.avro".

SparkSession spark = SparkSession.builder().master("local").getOrCreate();

Dataset<Row> df = spark.read().format("text")
  .load("Test.txt");

df.write().format("com.databricks.spark.avro")
  .save("/tmp/output");

**Exception:**

_**org.apache.spark.sql.AnalysisException: Failed to find data source: com.databricks.spark.avro. Please use Spark package http://spark-packages.org/package/databricks/spark-avro;**_
	at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:141)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:78)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:78)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:310)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
	at com.comcast.dart.spark.JavaSparkRDD.main(JavaSparkRDD.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:627)

**Maven dependencies:**

                    <dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-launcher_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.11</artifactId>
			<version>2.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.databricks</groupId>
			<artifactId>spark-avro_2.11</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
    		<groupId>org.apache.avro</groupId>
    		<artifactId>avro-mapred</artifactId>
   			 <version>1.8.1</version>
		</dependency>
		<dependency>
    		<groupId>org.apache.avro</groupId>
    		<artifactId>avro</artifactId>
   			<version>1.8.1</version>
		</dependency>

**Comment by Manikantan22** [comment]
Adding below settings in maven is not giving me fat jar. any idea what are all dependencies that I need to add?

<dependency>
        <groupId>com.databricks</groupId>
        <artifactId>spark-avro_2.11</artifactId>
        <version>3.0.0</version>
    </dependency>

**Comment by ssaminat** [comment]
Please give the solution for this question

**Comment by ssaminat** [comment]
Please give a maven dependencies that would be compatible. 
I am getting this error while running df.show()
java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
        at com.databricks.spark.avro.AvroRelation$$anonfun$buildScan$1$$anonfun$4.apply(AvroRelation.scala:133)

**Comment by mudasarsarwarhelix** [comment]
Please find below Maven which worked for me

<dependency>
	<groupId>org.apache.avro</groupId>
	<artifactId>avro</artifactId>
	<version>1.8.1</version>
</dependency>

<dependency>
	<groupId>com.databricks</groupId>
	<artifactId>spark-avro_2.11</artifactId>
	<version>3.1.0</version>
</dependency>

<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-sql_2.11</artifactId>
<version>2.0.2</version>
</dependency>

<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-core_2.11</artifactId>
	<version>2.0.2</version>
</dependency>
