### ISSUE TITLE
issue with below thing for map<string,string>

### ISSUE THREAD

**Issue by anandk89** [databricks/spark-avro#184]
This is my avro schema

```
{
  "type": "record",
  "name": "ecm",
  "namespace": "com.dis",
  "fields": [
    {
      "name": "fromMap",
      "type": {"type": "map", "values": ["null","string"]}
    }
  ]
}
```

and this is my json file 

```
{
  "fromMap": {
    "address": "abc@abccloud.com",
    "name": null,
    "contactId": null,
    "nameOrAddress": "abc@abccloud.com",
    "firstNameOrAddress": "sabc@abccloud.com"
  }
}
```

I am getting this issue again and again

```
C:\Users\anand.kamble\Desktop\test1>java -jar avro-tools-1.8.1.jar fromjson  --schema-file fromMap.avsc fromMap.json > fromMap.avro
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.apache.avro.AvroTypeException: Expected start-union. Got VALUE_STRING
        at org.apache.avro.io.JsonDecoder.error(JsonDecoder.java:698)
        at org.apache.avro.io.JsonDecoder.readIndex(JsonDecoder.java:441)
        at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:290)
        at org.apache.avro.io.parsing.Parser.advance(Parser.java:88)
        at org.apache.avro.io.ResolvingDecoder.readIndex(ResolvingDecoder.java:267)
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:178)
        at org.apache.avro.generic.GenericDatumReader.readMap(GenericDatumReader.java:321)
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:177)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:152)
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:240)
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:230)
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:174)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:152)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:144)
        at org.apache.avro.tool.DataFileWriteTool.run(DataFileWriteTool.java:99)
        at org.apache.avro.tool.Main.run(Main.java:87)
        at org.apache.avro.tool.Main.main(Main.java:76)
```

Kindly help.

**Comment by JoshRosen** [comment]
Are you actually using the Databricks `spark-avro` library here? I don't see it in any of your stacktraces. If you have more information on this issue, please comment and re-open.
