### ISSUE TITLE
NullPointerException when writing parquet from AVRO in Spark 2.0

### ISSUE THREAD

**Issue by ksindi** [databricks/spark-avro#188]
I'm loading AVRO files from S3 and writing them back as parquet.

```
from pyspark.sql import SparkSession
from pyspark.sql.types import *
    
spark = SparkSession.builder.appName("AvroParquet").enableHiveSupport().getOrCreate()
    
in_path = "s3://my-bucket/avro-path/*.avro"
out_path = "s3://my-bucket/parquet-path/output.parquet"
    
df = spark.read.format("com.databricks.spark.avro").load(in_path)
    
df.write.save(out_path, format="parquet")
```

For some reason I'm getting this `NullPointerException` when writing parquet. Might be when reading the avro looking at `java.io.ObjectInputStream.readObject0`.

 ```
   App > Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: org.apache.spark.SparkException: Task failed while writing rows
    App >   at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:270)
    App >   at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(InsertIntoHadoopFsRelationCommand.scala:143)
    App >   at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(InsertIntoHadoopFsRelationCommand.scala:143)
    App >   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
    App >   at org.apache.spark.scheduler.Task.run(Task.scala:85)
    App >   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    App >   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    App >   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    App >   at java.lang.Thread.run(Thread.java:745)
    App > Caused by: java.io.IOException: java.lang.NullPointerException
    App >   at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1284)
    App >   at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:174)
    App >   at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:65)
    App >   at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:65)
    App >   at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:89)
    App >   at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
    App >   at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:145)
    App >   at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:143)
    App >   at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(fileSourceInterfaces.scala:279)
    App >   at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(fileSourceInterfaces.scala:263)
    App >   at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:134)
    App >   at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:106)
    App >   at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
    App >   at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
    App >   at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
    App >   at org.apache.spark.sql.execution.datasources.DefaultWriterContainer$$anonfun$writeRows$1.apply$mcV$sp(WriterContainer.scala:262)
    App >   at org.apache.spark.sql.execution.datasources.DefaultWriterContainer$$anonfun$writeRows$1.apply(WriterContainer.scala:261)
    App >   at org.apache.spark.sql.execution.datasources.DefaultWriterContainer$$anonfun$writeRows$1.apply(WriterContainer.scala:261)
    App >   at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1359)
    App >   at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:267)
    App >   ... 8 more
    App > Caused by: java.lang.NullPointerException
    App >   at com.databricks.spark.avro.DefaultSource$SerializableConfiguration.tryOrIOException(DefaultSource.scala:217)
    App >   at com.databricks.spark.avro.DefaultSource$SerializableConfiguration.readObject(DefaultSource.scala:207)
    App >   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    App >   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    App >   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    App >   at java.lang.reflect.Method.invoke(Method.java:606)
    App >   at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
    App >   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
    App >   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
    App >   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    App >   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    App >   at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
    App >   at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$10.apply(TorrentBroadcast.scala:254)
    App >   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1321)
    App >   at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:255)
    App >   at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:189)
    App >   at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1277)
```

Just moved from 1.6 to 2.0 and not sure what the issue could be. Using the package `com.databricks:spark-avro_2.11:3.0.1`.

Seems to be related to #147 but that should be fixed with 3.0.1.

**Comment by ksindi** [comment]
One thing that might be different about my data is I have MapTypes such as `StructField("MapCol1", MapType(StringType(), StringType(), False), True)` and `StructField("MapCol2", MapType(StringType(), IntegerType(), False), True)`.

**Comment by ksindi** [comment]
Using Spark 2.0 I was able to convert AVRO to parquet locally as well as using EMR to S3. My best guess is that the issue is because of Spark settings from this third party service I'm using.

**Comment by ksindi** [comment]
These are my settings from this third party. Unfortunately I can't tell from here which configuration would cause this error.

**Spark Submit**
```
 --conf spark.driver.extraJavaOptions=-Djava.net.preferIPv4Stack=true --conf spark.driver.extraLibraryPath=/usr/lib/hadoop2/lib/native --conf spark.eventLog.compress=true --conf spark.eventLog.enabled=true --conf spark.executor.cores=2 --conf spark.executor.extraJavaOptions=-Djava.net.preferIPv4Stack=true --conf spark.executor.instances=2 --conf spark.executor.memory=5360M --conf spark.logConf=true --conf spark.speculation=false --conf spark.sql.qubole.split.computation=false --conf spark.ui.retainedJobs=33 --conf spark.ui.retainedStages=100 --conf spark.yarn.executor.memoryOverhead=1072 --conf spark.yarn.maxAppAttempts=1 --conf spark.master=yarn --conf spark.submit.deployMode=client
```

**Spark**
```
spark-defaults.conf:
spark.driver.extraJavaOptions -Djava.net.preferIPv4Stack=true
spark.driver.extraLibraryPath /usr/lib/hadoop2/lib/native
spark.eventLog.compress true
spark.eventLog.enabled true
spark.executor.cores 2
spark.executor.extraJavaOptions -Djava.net.preferIPv4Stack=true
spark.executor.instances 2
spark.executor.memory 5360M
spark.logConf true
spark.speculation false
spark.sql.qubole.split.computation false
spark.ui.retainedJobs 33
spark.ui.retainedStages 100
spark.yarn.executor.memoryOverhead 1072
spark.yarn.maxAppAttempts 1
spark.master yarn
spark.submit.deployMode client
```

**Hadoop**:
```
mapreduce.map.memory.mb=2144
mapreduce.reduce.java.opts=-Xmx1715m
mapreduce.reduce.memory.mb=2144
yarn.app.mapreduce.am.command-opts=-Xmx1715m
yarn.scheduler.minimum-allocation-vcores=1
yarn.scheduler.maximum-allocation-vcores=16
yarn.nodemanager.resource.memory-mb=25728
yarn.scheduler.minimum-allocation-mb=1024
yarn.app.mapreduce.am.resource.cpu-vcores=1
mapreduce.reduce.cpu.vcores=1
yarn.nodemanager.resource.cpu-vcores=16
yarn.app.mapreduce.am.resource.mb=2144
mapreduce.map.java.opts=-Xmx1715m
yarn.scheduler.maximum-allocation-mb=25728
mapreduce.map.cpu.vcores=1
mapreduce.task.io.sort.mb=848
dfs.datanode.max.transfer.threads=8192
dfs.datanode.max.xcievers=8192
```

**Comment by JoshRosen** [comment]
Are you _sure_ that you're using 3.0.1? The line numbers in your posted stacktrace don't seem to line up to the source. For instance,

```
com.databricks.spark.avro.DefaultSource$SerializableConfiguration.readObject(DefaultSource.scala:207)
```

where line 207 of that file is https://github.com/databricks/spark-avro/blob/v3.0.1/src/main/scala/com/databricks/spark/avro/DefaultSource.scala#L207

but `DefaultSource.readObject()` is, in fact, defined on line 260 in the 3.0.1 release: 

https://github.com/databricks/spark-avro/blob/v3.0.1/src/main/scala/com/databricks/spark/avro/DefaultSource.scala#L260

**Comment by ksindi** [comment]
Ah thanks for pointing this out. I'm going to close this issue because it's not really spark-avro specific.
