### ISSUE TITLE
Error reloading avro files in Pyspark Jupyter notebook "py4j.protocol.Py4JError: Answer from Java side is empty"

### ISSUE THREAD

**Issue by manugarri** [databricks/spark-avro#189]
I have spark 2.0.0 (pyspark). I run a notebook with the following command:
```
PYSPARK_DRIVER_PYTHON=ipython PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --port=7777" pyspark --packages com.databricks:spark-avro_2.10:3.0.1 --master local[8] --executor-memory 6400M --driver-memory 6400M
```
I have no problem in writing to avro:
```
train_data.write.format("com.databricks.spark.avro").save("/tmp/output2")

#open a part in python-avro to make sure it works:
from avro.datafile import DataFileReader
from avro.io import DatumReader
reader = DataFileReader(open("/tmp/output2/part-r-00000-20e91123-8f05-47e3-8769-836e87d659dd.avro", "rb"), DatumReader())
reader.__next__()
{... data looks ok ...}

```
However, when I try to read from that avro in spark by doing: 
```
reloaded_train_data = spark.read.format("com.databricks.spark.avro").load("/tmp/output2")
```
I get the following error (this is a subset, the shell keeps spitting out the same error until the notebook crashes):
```
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:34627)
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/tc_dmp/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-9eb740a850d1>", line 1, in <module>
    reloaded_train_data.take(1)
  File "/home/manuel/spark-2.0.0/python/pyspark/sql/dataframe.py", line 350, in take
    self._jdf, num)
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 933, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/manuel/spark-2.0.0/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: <unprintable Py4JJavaError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/tc_dmp/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1821, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'Py4JJavaError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 836, in send_command
    raise Py4JError("Answer from Java side is empty")
py4j.protocol.Py4JError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 695, in send_command
    response = connection.send_command(command)
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 840, in send_command
    raise Py4JNetworkError("Error while sending or receiving", e)
py4j.protocol.Py4JNetworkError: Error while sending or receiving

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 638, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 777, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuel/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 638, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:
...
```

Any idea why this is happening? I can serialize to text/json/csv with no problems.

**Comment by manugarri** [comment]
**Update:** I tried to read from avro in Scala spark-shell like this:
```
spark-shell --packages com.databricks:spark-avro_2.10:3.0.1 --master local[8]
scala> import com.databricks.spark.avro._
scala> import org.apache.spark.sql.SparkSession
scala> val spark = SparkSession.builder().master("local").getOrCreate()
scala> val df = spark.read.avro("/tmp/output2/part-r-00000-20e9c223-8f05-47e3-8769-836e87d659dd.avro")
scala> df.take(1)
```

That gave me a different error:
```
16/11/09 15:56:02 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1$$anon$1.<init>(DefaultSource.scala:208)
	at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:208)
	at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:154)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(fileSourceInterfaces.scala:279)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(fileSourceInterfaces.scala:263)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:116)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

**Comment by manugarri** [comment]
**Update2**: Bumping the spark-avro to `com.databricks:spark-avro_2.11:3.0.1` instead of `com.databricks:spark-avro_2.10:3.0.1` did the trick.

Apparently I have Scala 2.11 instead of 2.10.  I would have sworn I had 2.10 though.

Anyways, I'll close this issue, might be of use for future travellers.
