### ISSUE TITLE
Requiring .avro extension in Spark 2.0+

### ISSUE THREAD

**Issue by jon-gregg** [databricks/spark-avro#203]
I have a directory of Avro files in S3 that do not have .avro extensions.  I'm trying in Spark 2.0 to read from that directory, but it doesn't seem to be reading in the configuration changes.  Note that it appears I've set the configuration, but I'm still getting the message "Hadoop option "avro.mapred.ignore.inputs.without.extension" is set to true."

>>>
scala> spark.conf.set("avro.mapred.ignore.inputs.without.extension", "false")

scala> spark.conf.get("avro.mapred.ignore.inputs.without.extension")
res7: String = false

scala> spark.read.format("com.databricks.spark.avro").load("s3://path/to/my/dir").take(2)
java.io.FileNotFoundException: No Avro files found. Hadoop option "avro.mapred.ignore.inputs.without.extension" is set to true. Do all input files have ".avro" extension?
  at com.databricks.spark.avro.DefaultSource$$anonfun$2.apply(DefaultSource.scala:65)
  at com.databricks.spark.avro.DefaultSource$$anonfun$2.apply(DefaultSource.scala:65)
  at scala.Option.getOrElse(Option.scala:121)
  at com.databricks.spark.avro.DefaultSource.inferSchema(DefaultSource.scala:64)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
  at scala.Option.orElse(Option.scala:289)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:391)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
  ... 48 elided

**Comment by JoshRosen** [comment]
I think you need to set this in the Hadoop configuration used by Spark, not in SparkConf itself.

Try either

```
spark.sparkContext.hadoopConfiguration.set("avro.mapred.ignore.inputs.without.extension", "false")
```

or 

```
val conf = new SparkConf().set("spark.hadoop.avro.mapred.ignore.inputs.without.extension", "false")
val sc = new SparkContext(conf)
```

or use `--conf spark.hadoop.avro.mapred.ignore.inputs.without.extension=false` with `spark-submit` when launching your application (or set this key value pair in the cluster Spark settings dialog in Databricks).

Note that you should set these configurations prior to creating the SparkContext.

**Comment by itaysk** [comment]
I was struggling with the same thing, however I'm using pyspark.
I've tried the following with no success:
`spark.conf.set("avro.mapred.ignore.inputs.without.extension", "false")`
`spark.conf.set("spark.hadoop.avro.mapred.ignore.inputs.without.extension", "false")`
`SparkSession.builder.config("spark.hadoop.avro.mapred.ignore.inputs.without.extension","false")`
`SparkSession.builder.config("avro.mapred.ignore.inputs.without.extension","false")`

Eventually I found that this worked:
`spark.sparkContext._jsc.hadoopConfiguration().set('avro.mapred.ignore.inputs.without.extension', 'true')`

There's not enough documentation in this subject (configuring Hadoop through Spark) especially for Spark 2+, especially with pyspark. So if anyone here can explain what's going on it would be very helpful.

**Comment by posfaig** [comment]
Just an additional note if someone tries to do this in R. 
So I was trying to read avro files without .avro extension from HDFS using SparkR. Based on the previous comments this is how I finally made it work in R:

sc <- sparkR.session(
	appName = "read-avro-without-extension-example", 
	sparkPackages = c("com.databricks:spark-avro_2.11:3.0.1"))
sqlContext_ <- sparkR.newJObject("org.apache.spark.sql.SQLContext", sc)
sparkContext_ <- SparkR:::callJMethod(sqlContext_, "sparkContext")
hadoopConfiguration_ <- SparkR:::callJMethod(sparkContext_, "hadoopConfiguration")
SparkR:::callJMethod(hadoopConfiguration_, "set", "avro.mapred.ignore.inputs.without.extension", "false")    
spark_df <- read.df("hdfs://hdfscluster/path/to/avro/file", "com.databricks.spark.avro")

**Comment by AjarKeen** [comment]
A similar approach also works in sparklyr:

```r
library(sparklyr)

conf <- spark_config()
conf$spark.hadoop.avro.mapred.ignore.inputs.without.extension <- FALSE

sc <- spark_connect(master = "yarn-client",
                    spark_home = "/usr/lib/spark",
                    config = conf,
                    packages = "org.apache.hadoop:hadoop-aws:2.7.3")

```

**Comment by ganeshharugeri** [comment]
I was having trouble in accessing S3 buckets content which had avro files using sparklyr. The error thrown at me was s3a fie not found.

I updated accordingly AjarKeen's code to update 'packages' qualifier.

```
conf <- spark_config()
sc <- spark_connect(master = "yarn-client",
                    spark_home = "/usr/lib/spark",
                    config = conf,
                    packages = "org.apache.hadoop:hadoop-aws:2.7.3")
```

Now I am successfully able to read from S3 buckets to R session using sparklyr and sparkavro.

**Comment by peterbengkui** [comment]
for Sparksession:
` spark = SparkSession.builder().appName(appName).config("spark.hadoop.avro.mapred.ignore.inputs.without.extension", "false").getOrCreate();`
