### ISSUE TITLE
Error while generating AVRO files

### ISSUE THREAD

**Issue by vara-bonthu** [databricks/spark-avro#208]
I am getting the following error while I try to create AVRO files using the following code.

Its successfully creating the SQLframe using CSV and the schema but throwing an error when I try to write into avro using df.write.avro(outputDirectory). Am I missing anything? 

I have attached the full log.

val df = spark.read
      .format("com.databricks.spark.csv")
      .option("delimiter", "|")
      .option("header", "false")
      .option("inferSchema", "true")
      .schema(sqlSchema)            // sqlSchema converted from AVRO schma from previous step
      .load(zeusInputDigitalFile)  // csv files with pipe seprated
     .write.avro(outputDirectory) //output directory location

Error Log
----------
17/01/19 14:24:07 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
17/01/19 14:24:07 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vara-bonthu** [comment]
Just found out that it's failing only with spark version 2.1.0 and it works fine with 2.0.0

**Comment by Venkateshgovind** [comment]
Same problem. it worked with 2.0.1 but not with spark 2.1.0

**Comment by JoshRosen** [comment]
I've just released version 3.2.0, which adds support for Spark 2.1.0: https://github.com/databricks/spark-avro/releases/tag/v3.2.0

**Comment by Venkateshgovind** [comment]
Thank you! Will try it out

**Comment by sinasohangirsc** [comment]
Is there any updates on how to get this working with Spark 2.2.0?
