### ISSUE TITLE
StackOverFlowError : When added where clause in the query

### ISSUE THREAD

**Issue by mkanchwala** [databricks/spark-avro#27]
When I Tried to add a Where clause in the query :

import org.apache.hadoop.hdfs.DistributedFileSystem
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.apache.spark.sql.SQLContext
import com.databricks.spark.avro._
object SparkAvroRW {
private val AppName = "SparkAvroRW"
def main(args: Array[String]) {

    //Defining the context and Initializing the App
    val sparkConf = new SparkConf() setAppName(AppName) setMaster("local")
    val sc = new SparkContext(sparkConf)
        val input = args(0)
    val output = args(1)
    val sqlContext = new SQLContext(sc);
    val students = sqlContext.avroFile(input);
    val sRDD =   students.collect;
    print(sRDD.length)
    students.registerTempTable("student")
    val studentsRDD = sqlContext.sql("SELECT * FROM student where id > 20").saveAsAvroFile(output) 
  }
}

It Throws the following error : 

Exception in thread "main" java.lang.StackOverflowError
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)

**Comment by vlyubin** [comment]
This problem doesn't occur because of spark-avro. I'm not sure why it is happening in the first place, but since people saw it in other contexts where registerTempTable was used, I would assume that somehow problem lies there. I guess you've already found that out though.

https://github.com/databricks/reference-apps/issues/46
http://apache-spark-user-list.1001560.n3.nabble.com/Spark-SQL-Stackoverflow-error-td12086.html

**Comment by vlyubin** [comment]
Closing this, because it isn't a spark-avro issue.

**Comment by mkanchwala** [comment]
I have to use transformations and actions instead of Where clause

**Comment by lxn130730** [comment]
how to do that?? can you please share the code
