### ISSUE TITLE
Please provide a working sample for python. I need to do a spark sql query on an avro file containing json data.

### ISSUE THREAD

**Issue by krdeepakio** [databricks/spark-avro#64]
I started the shell using --jars option
./bin/pyspark --jars /root/krd/temp/spark-avro_2.10-1.0.0.jar

Tried loading an avro file

>>> df = sqlContext.load("/root/krd/temp/part-r-00000.avro", "com.databricks.spark.avro")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/spark/spark-1.4.0-bin-hadoop2.4/python/pyspark/sql/context.py", line 475, in load
    return self.read.load(path, source, schema, **options)
  File "/root/spark/spark-1.4.0-bin-hadoop2.4/python/pyspark/sql/readwriter.py", line 94, in load
    return self._df(self._jreader.load(path))
  File "/root/spark/spark-1.4.0-bin-hadoop2.4/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/root/spark/spark-1.4.0-bin-hadoop2.4/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o48.load.
: java.lang.RuntimeException: Failed to load class for data source: com.databricks.spark.avro
	at scala.sys.package$.error(package.scala:27)

Thank you for the help.

**Comment by ksindi** [comment]
I am having a similar issue with `episodes.avro` example. Running Spark 1.3.1 and spark-avro_2.10-1.0.0.jar.

```
>>> df = sqlContext.load(".../episodes.avro", source="com.databricks.spark.avro")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/spark/python/pyspark/sql/context.py", line 442, in load
    df = self._ssql_ctx.load(source, joptions)
  File "/home/hadoop/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/home/hadoop/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o25.load.
: java.lang.RuntimeException: Failed to load class for data source: com.databricks.spark.avro
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.sources.ResolvedDataSource$.lookupDataSource(ddl.scala:194)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:205)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:697)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment]
I'm not super familiar with this Avro library, so I don't know how to fix this issue, but I think that we should add automated Travis tests which try to run this library using PySpark.

**Comment by ksindi** [comment]
Issue might be from also having Hive installed: https://issues.apache.org/jira/plugins/servlet/mobile#issue/SPARK-8365

Removing Hive, I now get the error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o25.load.
: java.lang.NoClassDefFoundError: org/apache/avro/SchemaBuilder$BaseTypeBuilder
	at com.databricks.spark.avro.AvroRelation.<init>(AvroRelation.scala:59)
	at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:41)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:219)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:697)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.avro.SchemaBuilder$BaseTypeBuilder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more
```

**Comment by JoshRosen** [comment]
Ah, I see the problem: as #65 points out, `--jars` is only including `spark-avro` but does not automatically include transitive dependencies.  Possible solutions include passing the Avro jar as an additional `--jar` argument (as shown in #65) or using the `--packages` instead of `--jars`, since `--packages` will handle transitive dependencies automatically.

**Comment by JoshRosen** [comment]
The README has been updated to recommend `--packages`, so I'm going to mark this issue as fixed.
