### ISSUE TITLE
PySpark episodes example gives NoClassDefFoundError

### ISSUE THREAD

**Issue by ksindi** [databricks/spark-avro#65]
Spark 1.3.1, spark-avro_2.10-1.0.0 and Hadoop 2.4.0.

Running the example
```
>>> from pyspark.sql import SQLContext
>>> sqlContext = SQLContext(sc)
>>> df = sqlContext.load("episodes.avro", source="com.databricks.spark.avro")
```
gives me the following error:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o25.load.
: java.lang.NoClassDefFoundError: org/apache/avro/SchemaBuilder$BaseTypeBuilder
	at com.databricks.spark.avro.AvroRelation.<init>(AvroRelation.scala:59)
	at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:41)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:219)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:697)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.avro.SchemaBuilder$BaseTypeBuilder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more
```

**Comment by ksindi** [comment]
Fixed issue. I had to include the Apache Avro jar:
```
./bin/pyspark --jars avro-1.7.7.jar,spark-avro_2.10-1.0.0.jar 
```
