### ISSUE TITLE
missing support for spark DateType

### ISSUE THREAD

**Issue by Roen00** [databricks/spark-avro#67]
Hi, 
I want to save the data, loaded from the database, to the HDFS.
In the DB schema there is a field which has an "ansidate" type.
When I load the data to the dataframes the field with the date type is converted to spark.DateType.
And finally when I'm trying to save the dataframe on the HDFS the application is crushing with given stack trace:

```
 INFO DAGScheduler: Job 8 finished: saveAsHadoopFile at AvroSaver.scala:54, took 1.289520 s
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected type DateType.
        at com.databricks.spark.avro.SchemaConverters$.com$databricks$spark$avro$SchemaConverters$$convertFieldTypeToAvro(SchemaConverters.scala:184)
        at com.databricks.spark.avro.SchemaConverters$$anonfun$convertStructToAvro$1.apply(SchemaConverters.scala:103)
        at com.databricks.spark.avro.SchemaConverters$$anonfun$convertStructToAvro$1.apply(SchemaConverters.scala:99)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at com.databricks.spark.avro.SchemaConverters$.convertStructToAvro(SchemaConverters.scala:99)
        at com.databricks.spark.avro.AvroSaver$.save(AvroSaver.scala:51)
        at com.databricks.spark.avro.package$AvroDataFrame.saveAsAvroFile(package.scala:34)
        at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:78)
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:308)
        at org.apache.spark.sql.DataFrame.save(DataFrame.scala:1123)
        at org.apache.spark.sql.DataFrame.save(DataFrame.scala:1083)
        at com.barclays.mercury.junoop.bcbs.SparkExperimentalJob$$anonfun$main$3.apply(SparkExperimentalJob.scala:53)
        at com.barclays.mercury.junoop.bcbs.SparkExperimentalJob$$anonfun$main$3.apply(SparkExperimentalJob.scala:52)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.barclays.mercury.junoop.bcbs.SparkExperimentalJob$.main(SparkExperimentalJob.scala:52)
        at com.barclays.mercury.junoop.bcbs.SparkExperimentalJob.main(SparkExperimentalJob.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
^
```

Saving the DateType also doesn't work in the parquet file format in spark core library.
I also wonder what is the reason for that it's not implemented.

Did you achieve the solution for this?

**Comment by blrnw3** [comment]
:+1:

**Comment by nihed** [comment]
based on this requirement and on my personnel need, I provide this solution https://github.com/databricks/spark-avro/pull/124

**Comment by blrnw3** [comment]
Thanks nihed. This is a critical issue for me, and needs attention. 👍

**Comment by vlyubin** [comment]
https://github.com/databricks/spark-avro/pull/124 is merged to master and 3.2

**Comment by blrnw3** [comment]
When is this gonna be released, please? 🙂  I'm using 3.2 and this fix is not there

**Comment by Roen00** [comment]
Shouldn't it be added to "Supported types for Avro" in readme file?

**Comment by rohanahire88** [comment]
Hi. I am using packages=com.databricks:spark-avro_2.11:3.2.0 and the date support  is not added in it. I am storing a date datatype column from sparksql into an avro file and it gives me the error, 
 com.databricks.spark.avro.SchemaConverters$IncompatibleSchemaException: Unexpected type DateType.

**Comment by nihed** [comment]
Hi, 
3.2.0 don't provide dateType like you can see in this link : 
https://github.com/databricks/spark-avro/tree/v3.2.0

**Comment by rohanahire88** [comment]
Thanks for your reply. Is there a newer version which i could use?

**Comment by jainank** [comment]
If 3.2.0 don't have it then which version should we use to get support for DateType. Could you please reply with maven dependency tag.
