### ISSUE TITLE
Support for Avro with "bytes" schema (BinaryType)

### ISSUE THREAD

**Issue by mamhamed** [databricks/spark-avro#68]
Currently "bytes" schema is not supported. However "bytes" schema is used (and recommended to be used) as output format for some MR jobs. 

**Example of use case:**

> To write to Avro data files from a streaming program, specify org.apache.avro.mapred.AvroTextOutputFormat as the output format. This output format will create Avro data files with a "bytes" schema,...
> [Cloudera Avro Usage](http://www.cloudera.com/content/cloudera/en/documentation/cdh4/v4-2-1/CDH4-Installation-Guide/cdh4ig_topic_26_6.html)

an attempt to load an avro file with bytes schema will result in the following error message:

```
Py4JJavaError: An error occurred while calling o37.load.
: java.lang.RuntimeException: Avro files must contain Records to be read, type BinaryType not supported
    at scala.sys.package$.error(package.scala:27)
    at com.databricks.spark.avro.AvroRelation.<init>(AvroRelation.scala:75)
    at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:55)
    at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:219)
    at org.apache.spark.sql.SQLContext.load(SQLContext.scala:697)
    at org.apache.spark.sql.SQLContext.load(SQLContext.scala:685)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
    at py4j.Gateway.invoke(Gateway.java:259)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:207)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by JoshRosen** [comment]
I believe that this may have been fixed in a newer release. Since this ticket is over a year old, I'm not sure. Therefore, I'm going to optimistically close it to declutter the backlog, but please file a new ticket if this is still a problem. Thanks!

**Comment by jzako** [comment]
Just an update. I created avro file with Schema.Type.BYTES and put each proto message (using message.toByteArray()) to that file.
But spark-avro still seems not support bytes array:
`scala> val df = sqlContext.read.avro("/Users/jesse_zha/data/part-r-00000.avro")
java.lang.RuntimeException: Avro schema cannot be converted to a Spark SQL StructType:

"bytes"

  at com.databricks.spark.avro.DefaultSource.inferSchema(DefaultSource.scala:93)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at scala.Option.orElse(Option.scala:289)
  at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$getOrInferFileFormatSchema(DataSource.scala:183)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
  at com.databricks.spark.avro.package$AvroDataFrameReader$$anonfun$avro$2.apply(package.scala:34)
  at com.databricks.spark.avro.package$AvroDataFrameReader$$anonfun$avro$2.apply(package.scala:34)
  ... 50 elided`

Lauched spark-shell with --packages com.databricks:spark-avro_2.11:3.2.0
