### ISSUE TITLE
Append Mode is not Enabled for AvroSaver

### ISSUE THREAD

**Issue by mkanchwala** [databricks/spark-avro#75]
This is some serious issue as we have 68TB of Data and we need to append the files in the folder hierarchy, We can't do overwrite or delete and write it again. 

```
java.lang.RuntimeException: Append mode is not supported by com.databricks.spark.avro.DefaultSource
        at scala.sys.package$.error(package.scala:27)
        at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:63)
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:309)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:135)
        at org.apache.spark.sql.DataFrame.save(DataFrame.scala:1672)
        at com.johndeere.dataclassifier.app.DataClassifierApp$$anonfun$4.apply(DataClassifierApp.scala:82)
        at com.johndeere.dataclassifier.app.DataClassifierApp$$anonfun$4.apply(DataClassifierApp.scala:39)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
15/08/20 12:26:28 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 1.0 (TID 21, localhost): java.lang.RuntimeException: Append mode is not supported by com.databricks.spark.avro.DefaultSource
        at scala.sys.package$.error(package.scala:27)
        at com.databricks.spark.avro.DefaultSource.createRelation(DefaultSource.scala:63)
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:309)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:135)
        at org.apache.spark.sql.DataFrame.save(DataFrame.scala:1672)
        at com.johndeere.dataclassifier.app.DataClassifierApp$$anonfun$4.apply(DataClassifierApp.scala:82)
        at com.johndeere.dataclassifier.app.DataClassifierApp$$anonfun$4.apply(DataClassifierApp.scala:39)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mkanchwala** [comment]
Also I tried to apply CustomPartitioner But I found that it is also not working with it. Can you guys help me out on this?

**Comment by JoshRosen** [comment]
I think we might actually support this now. I'm going to optimistically close this ticket, but please re-open if this is still an issue.
