### ISSUE TITLE
Potential issue when reading Avro files generated from Java classes

### ISSUE THREAD

**Issue by JoshRosen** [databricks/spark-avro#90]
See report of error at https://stackoverflow.com/questions/32503059/how-to-read-avro-files-generated-from-java-class-using-spark-shell-when-the-so

It seems that class cast exceptions can occur when loading Avro files that were generated from Java objects:

```java
A cannot be cast to org.apache.avro.generic.IndexedRecord
    at org.apache.avro.generic.GenericData.setField(GenericData.java:569)
    at org.apache.avro.generic.GenericData.setField(GenericData.java:586)
    at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
    at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
    at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
    at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
    at org.apache.avro.file.DataFileStream.next(DataFileStream.java:233)
    at org.apache.avro.mapred.AvroRecordReader.next(AvroRecordReader.java:66)
    at org.apache.avro.mapred.AvroRecordReader.next(AvroRecordReader.java:32)
    at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:248)
    at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:216)
    at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:71)
    at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$class.isEmpty(Iterator.scala:256)
    at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1157)
    at com.databricks.spark.avro.AvroRelation$$anonfun$buildScan$1$$anonfun$4.apply(AvroRelation.scala:127)
    at com.databricks.spark.avro.AvroRelation$$anonfun$buildScan$1$$anonfun$4.apply(AvroRelation.scala:126)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
    at org.apache.spark.rdd.UnionRDD.compute(UnionRDD.scala:87)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
    at org.apache.spark.scheduler.Task.run(Task.scala:70)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattomatic** [comment]
Is there a better workaround now than the one referenced on SO?

**Comment by dale6john** [comment]
does anyone have an update to this?   The alternative is DataFrames is broken for a year.  Seems kind of unsatisfactory.

**Comment by JoshRosen** [comment]
I'm totally happy to help debug this, but it would be useful to have a standalone reproduction or an updated stacktrace. Could you post either here?

**Comment by matteobovetti** [comment]
I have the same problem with an avro with this schema:

`
{
  "type" : "record",
  "name" : "AgendaUpdate",
  "namespace": "my.namespace",
  "fields" : [ {
    "name" : "pod",
    "type" : "string"
  }, {
    "name" : "dataMisura",
    "type" : {
      "type" : "int",
      "logicalType" : "date"
    }
  }, {
    "name" : "misuratore",
    "type" : "string"
  }, {
    "name" : "codContrattoDp",
    "type" : "string"
  }, {
    "name" : "statoPod",
    "type" : {
      "type" : "enum",
      "name" : "PodDispatchStatus",
      "symbols" : [ "DISPATCHABLE", "DISPATCHED", "WAITING_FOR_MEASURE", "NOT_DISPATCHABLE", "CANCELED", "UNDEFINED" ]
    }
  }, {
    "name" : "statoFinale",
    "type" : {
      "type" : "enum",
      "name" : "FinalDispatchStatus",
      "symbols" : [ "DISPATCHABLE", "DISPATCHED", "WAITING_FOR_MEASURE", "NOT_DISPATCHABLE", "CANCELED", "UNDEFINED" ]
    }
  }, {
    "name" : "dataSmistamento",
    "type" : [ {
      "type" : "int",
      "logicalType" : "date"
    }, "null" ],
    "default" : null
  }, {
    "name" : "nomeFile",
    "type" : [ "string", "null" ]
  }, {
    "name" : "codLet",
    "type" : "string"
  } ]
}
`

and my.namespace.AgendaUpdate is a Java Object used for write data inside the avro file.

**Comment by frutchey** [comment]
I was having this issue, but then looked at [source](https://github.com/apache/parquet-mr/blob/master/parquet-avro/src/test/java/org/apache/parquet/avro/TestReflectReadWrite.java) and found that using 
`Configuration conf = new Configuration();
conf.setBoolean(AvroReadSupport.AVRO_COMPATIBILITY, false);
 AvroReadSupport.setAvroDataSupplier(conf, ReflectDataSupplier.class);

was critical, as was adding the "ReflectData.get()" GenericData to the writer like
`ParquetWriter<T> parquetWriter = AvroParquetWriter.<T>builder(path).withDataModel(ReflectData.get()).build();`
		`
